# Generated by Django 2.1.7 on 2019-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demostatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
