# Generated by Django 3.1.4 on 2020-12-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demostat', '0002_auto_20190322_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='emphasise',
            field=models.BooleanField(default=False),
        ),
    ]
